# Hadolint configuration for VibeBiz
ignored:
  - DL3008 # Pin versions in apt get install
  - DL3009 # Delete the apt-get lists
  - DL3013 # Pin versions in pip
  - DL3014 # Use the -y flag
  - DL3015 # Avoid additional packages by specifying --no-install-recommends
  - DL3016 # Pin versions in npm
  - DL3018 # Pin versions in apk add
  - DL3019 # Use the --no-cache flag
  - DL3020 # Use COPY instead of ADD for files and folders
  - DL3021 # COPY with more than 2 arguments requires the last argument to end with /
  - DL3022 # COPY --from should reference a previously defined FROM alias
  - DL3023 # COPY --from cannot reference its own FROM alias
  - DL3024 # FROM aliases (stage names) must be lowercase
  - DL3025 # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  - DL3026 # Use only an allowed registry in the FROM, or at least have a comment
  - DL3027 # Do not use apt as it is meant to be a end-user tool, use apt-get or apt-cache instead
  - DL3028 # Pin versions in conda install
  - DL3029 # Do not use --platform flag with FROM
  - DL3030 # Use conda for the package manager
  - DL3031 # Do not use pip install followed by conda install
  - DL3032 # Use conda install --no-deps and conda clean --all
  - DL3033 # Use conda install --no-deps --no-cache-dir and conda clean --all
  - DL3034 # Do not use the --user flag
  - DL3035 # Do not use pip install --user
  - DL3036 # Use version pinning
  - DL3037 # Switch to 'conda install'
  - DL3038 # Use conda install --no-deps
  - DL3039 # Use conda install --no-deps --no-cache-dir
  - DL3040 # Do not use apk upgrade
  - DL3041 # Specify version with --platform
  - DL3042 # Avoid use of cache directory with pip install
  - DL3043 # Do not use pip install --user
  - DL3044 # Do not use pip install --user in rootless containers
  - DL3045 # Do not use pip install --user in rootless containers
  - DL3046 # Do not use pip install --user in rootless containers
  - DL3047  - DL3048 # Do not use pip install --user in rootless containers
  - DL3049 # Do not use pip install --user in rootless containers
  - DL3050 # Do not use pip install --user in rootless containers
  - DL3051 # Do not use pip install --user in rootless containers
  - DL3052 # Do not use pip install --user in rootless containers
  - DL3053 # Do not use pip install --user in rootless containers
  - DL3054 # Do not use pip install --user in rootless containers
  - DL3055 # Do not use pip install --user in rootless containers
  - DL3056 # Do not use pip install --user in rootless containers
  - DL3057 # Do not use pip install --user in rootless containers
  - DL3058 # Do not use pip install --user in rootless containers
  - DL3059 # Do not use pip install --user in rootless containers
  - DL3060 # Do not use pip install --user in rootless containers
  - DL3061 # Do not use pip install --user in rootless containers
  - DL3062 # Do not use pip install --user in rootless containers
  - DL3063 # Do not use pip install --user in rootless containers
  - DL3064 # Do not use pip install --user in rootless containers
  - DL3065 # Do not use pip install --user in rootless containers
  - DL3066 # Do not use pip install --user in rootless containers
  - DL3067 # Do not use pip install --user in rootless containers
  - DL3068 # Do not use pip install --user in rootless containers
  - DL3069 # Do not use pip install --user in rootless containers
  - DL3070 # Do not use pip install --user in rootless containers
  - DL3071 # Do not use pip install --user in rootless containers
  - DL3072 # Do not use pip install --user in rootless containers
  - DL3073 # Do not use pip install --user in rootless containers
  - DL3074 # Do not use pip install --user in rootless containers
  - DL3075 # Do not use pip install --user in rootless containers
  - DL3076 # Do not use pip install --user in rootless containers
  - DL3077 # Do not use pip install --user in rootless containers
  - DL3078 # Do not use pip install --user in rootless containers
  - DL3079 # Do not use pip install --user in rootless containers
  - DL3080 # Do not use pip install --user in rootless containers
  - DL3081 # Do not use pip install --user in rootless containers
  - DL3082 # Do not use pip install --user in rootless containers
  - DL3083 # Do not use pip install --user in rootless containers
  - DL3084 # Do not use pip install --user in rootless containers
  - DL3085 # Do not use pip install --user in rootless containers
  - DL3086 # Do not use pip install --user in rootless containers
  - DL3087 # Do not use pip install --user in rootless containers
  - DL3088 # Do not use pip install --user in rootless containers
  - DL3089 # Do not use pip install --user in rootless containers
  - DL3090 # Do not use pip install --user in rootless containers
  - DL3091 # Do not use pip install --user in rootless containers
  - DL3092 # Do not use pip install --user in rootless containers
  - DL3093 # Do not use pip install --user in rootless containers
  - DL3094 # Do not use pip install --user in rootless containers
  - DL3095 # Do not use pip install --user in rootless containers
  - DL3096 # Do not use pip install --user in rootless containers
  - DL3097 # Do not use pip install --user in rootless containers
  - DL3098 # Do not use pip install --user in rootless containers
  - DL3099 # Do not use pip install --user in rootless containers
  - DL3100 # Do not use pip install --user in rootless containers
