[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vibebiz-saas-template"
version = "0.1.0"

[tool.setuptools]
packages = ["apps", "packages", "services"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I", "N", "D"]

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
